2020-09-28 18:15:17.482 [ERR] [session.go:299] recvLoop error error: read tcp 127.0.0.1:17012->127.0.0.1:61249: wsarecv: An existing connection was forcibly closed by the remote host., remoteAddr: 127.0.0.1:61249,  localAddr: 127.0.0.1:17012, sessionid: 1
2020-09-28 18:15:17.482 [ERR] [viper.go:732] recvLoop panic:ProcApp OnClosed....goroutine 66 [running]:
runtime/debug.Stack(0xc0003c3d40, 0x142fe20, 0x15af6a0)
	D:/Go/src/runtime/debug/stack.go:24 +0xa5
github.com/giant-tech/go-service/framework/net/internal/internal.(*Session).recvLoop.func1()
	C:/Users/yekoufeng/go/pkg/mod/github.com/giant-tech/go-service@v0.0.9/framework/net/internal/internal/session.go:267 +0x5e
panic(0x142fe20, 0x15af6a0)
	D:/Go/src/runtime/panic.go:969 +0x176
github.com/giant-tech/go-service/framework/app/internal.(*ProcApp).OnClosed(0xc00038c780)
	C:/Users/yekoufeng/go/pkg/mod/github.com/giant-tech/go-service@v0.0.9/framework/app/internal/appProc.go:42 +0x45
github.com/giant-tech/go-service/framework/net/internal/internal.(*Session).callonClosed(0xc0003c6000)
	C:/Users/yekoufeng/go/pkg/mod/github.com/giant-tech/go-service@v0.0.9/framework/net/internal/internal/session.go:428 +0x59
github.com/giant-tech/go-service/framework/net/internal/internal.(*Session).recvLoop(0xc0003c6000)
	C:/Users/yekoufeng/go/pkg/mod/github.com/giant-tech/go-service@v0.0.9/framework/net/internal/internal/session.go:301 +0x239
created by github.com/giant-tech/go-service/framework/net/internal/internal.(*Session).Start
	C:/Users/yekoufeng/go/pkg/mod/github.com/giant-tech/go-service@v0.0.9/framework/net/internal/internal/session.go:112 +0x65

2020-09-28 18:46:32.654 [ERR] [session.go:299] recvLoop error error: read tcp 127.0.0.1:64464->127.0.0.1:17012: wsarecv: An existing connection was forcibly closed by the remote host., remoteAddr: 127.0.0.1:17012,  localAddr: 127.0.0.1:64464, sessionid: 1
2020-09-28 18:46:32.655 [ERR] [viper.go:732] recvLoop panic:ProcApp OnClosed....goroutine 53 [running]:
runtime/debug.Stack(0xc00033dd40, 0x105fe20, 0x11df660)
	D:/Go/src/runtime/debug/stack.go:24 +0xa5
github.com/giant-tech/go-service/framework/net/internal/internal.(*Session).recvLoop.func1()
	C:/Users/yekoufeng/go/pkg/mod/github.com/giant-tech/go-service@v0.0.9/framework/net/internal/internal/session.go:267 +0x5e
panic(0x105fe20, 0x11df660)
	D:/Go/src/runtime/panic.go:969 +0x176
github.com/giant-tech/go-service/framework/app/internal.(*ProcApp).OnClosed(0xc000312f40)
	C:/Users/yekoufeng/go/pkg/mod/github.com/giant-tech/go-service@v0.0.9/framework/app/internal/appProc.go:42 +0x45
github.com/giant-tech/go-service/framework/net/internal/internal.(*Session).callonClosed(0xc000340000)
	C:/Users/yekoufeng/go/pkg/mod/github.com/giant-tech/go-service@v0.0.9/framework/net/internal/internal/session.go:428 +0x59
github.com/giant-tech/go-service/framework/net/internal/internal.(*Session).recvLoop(0xc000340000)
	C:/Users/yekoufeng/go/pkg/mod/github.com/giant-tech/go-service@v0.0.9/framework/net/internal/internal/session.go:301 +0x239
created by github.com/giant-tech/go-service/framework/net/internal/internal.(*Session).Start
	C:/Users/yekoufeng/go/pkg/mod/github.com/giant-tech/go-service@v0.0.9/framework/net/internal/internal/session.go:112 +0x65

2020-09-28 18:46:32.768 [ERR] [serviceA.go:51] AsyncCall: session closed
2020-09-28 18:46:38.818 [ERR] [appNet.go:308] Connect failed. 4294967346 to 4294967348 Addr 127.0.0.1:17012, error:dial tcp 127.0.0.1:17012: connectex: No connection could be made because the target machine actively refused it.
2020-09-28 18:46:41.768 [ERR] [serviceProxy.go:77] SProxy.SyncCall, remote retData.Err: call timeout
2020-09-28 18:46:41.768 [ERR] [serviceA.go:61] SyncCall:call timeout
2020-09-28 18:46:41.768 [ERR] [serviceA.go:51] AsyncCall: session closed
2020-09-28 18:46:43.801 [ERR] [appNet.go:308] Connect failed. 4294967346 to 4294967348 Addr 127.0.0.1:17012, error:dial tcp 127.0.0.1:17012: connectex: No connection could be made because the target machine actively refused it.
2020-09-28 18:46:46.769 [ERR] [serviceProxy.go:77] SProxy.SyncCall, remote retData.Err: call timeout
2020-09-28 18:46:46.769 [ERR] [serviceA.go:61] SyncCall:call timeout
2020-09-28 18:46:46.771 [ERR] [serviceA.go:51] AsyncCall: session closed
2020-09-28 18:46:48.828 [ERR] [appNet.go:308] Connect failed. 4294967346 to 4294967348 Addr 127.0.0.1:17012, error:dial tcp 127.0.0.1:17012: connectex: No connection could be made because the target machine actively refused it.
2020-09-28 18:46:51.768 [ERR] [serviceProxy.go:77] SProxy.SyncCall, remote retData.Err: call timeout
2020-09-28 18:46:51.768 [ERR] [serviceA.go:61] SyncCall:call timeout
2020-09-28 18:46:51.768 [ERR] [serviceA.go:51] AsyncCall: session closed
2020-09-28 18:46:53.811 [ERR] [appNet.go:308] Connect failed. 4294967346 to 4294967348 Addr 127.0.0.1:17012, error:dial tcp 127.0.0.1:17012: connectex: No connection could be made because the target machine actively refused it.
2020-09-28 18:46:56.768 [ERR] [serviceProxy.go:77] SProxy.SyncCall, remote retData.Err: call timeout
2020-09-28 18:46:56.768 [ERR] [serviceA.go:61] SyncCall:call timeout
2020-09-28 18:46:56.768 [ERR] [serviceA.go:51] AsyncCall: session closed
2020-09-28 18:46:58.819 [ERR] [appNet.go:308] Connect failed. 4294967346 to 4294967348 Addr 127.0.0.1:17012, error:dial tcp 127.0.0.1:17012: connectex: No connection could be made because the target machine actively refused it.
2020-09-28 18:47:01.768 [ERR] [serviceProxy.go:77] SProxy.SyncCall, remote retData.Err: call timeout
2020-09-28 18:47:01.768 [ERR] [serviceA.go:61] SyncCall:call timeout
2020-09-28 18:47:01.768 [ERR] [serviceA.go:51] AsyncCall: session closed
2020-09-28 18:47:06.768 [ERR] [serviceProxy.go:77] SProxy.SyncCall, remote retData.Err: call timeout
2020-09-28 18:47:06.768 [ERR] [serviceA.go:61] SyncCall:call timeout
2020-09-28 18:47:06.768 [ERR] [serviceA.go:51] AsyncCall: session closed
2020-09-28 18:47:11.768 [ERR] [serviceProxy.go:77] SProxy.SyncCall, remote retData.Err: call timeout
2020-09-28 18:47:11.768 [ERR] [serviceA.go:61] SyncCall:call timeout
2020-09-28 18:47:11.768 [ERR] [serviceA.go:51] AsyncCall: session closed
2020-09-28 18:52:22.953 [ERR] [session.go:299] recvLoop error error: read tcp 127.0.0.1:17012->127.0.0.1:65156: wsarecv: An existing connection was forcibly closed by the remote host., remoteAddr: 127.0.0.1:65156,  localAddr: 127.0.0.1:17012, sessionid: 1
